### ISSUE TITLE
NoMethodError (undefined method `[]' for nil:NilClass):

### ISSUE THREAD

**Issue by secretfader** [plataformatec/devise#2065]
I just started a new Rails 3.2.8 app, and keep receiving this error. It occurs anytime I directly hit a Devise controller, or use the authenticate_user! filter.

```
Started GET "/users/sign_in" for 127.0.0.1 at 2012-09-17 22:55:00 -0500
Processing by Devise::SessionsController#new as HTML
Completed 500 Internal Server Error in 0ms

NoMethodError (undefined method `[]' for nil:NilClass):
  warden (1.2.1) lib/warden/session_serializer.rb:31:in `fetch'
  warden (1.2.1) lib/warden/proxy.rb:212:in `user'
  warden (1.2.1) lib/warden/proxy.rb:318:in `_perform_authentication'
  warden (1.2.1) lib/warden/proxy.rb:104:in `authenticate'
  warden (1.2.1) lib/warden/proxy.rb:114:in `authenticate?'
  /Users/nicholaswyoung/.rvm/gems/ruby-1.9.3-p194-dev/bundler/gems/devise-8c7bf7dd15af/app/controllers/devise_controller.rb:124:in `require_no_authentication'
  activesupport (3.2.8) lib/active_support/callbacks.rb:418:in `_run__225892201280898280__process_action__4512450677408931391__callbacks'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.8) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.8) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.8) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  actionpack (3.2.8) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.8) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.8) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.8) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.8) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:36:in `call'
  actionpack (3.2.8) lib/action_dispatch/routing/mapper.rb:42:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:600:in `call'
  mongoid (3.0.6) lib/rack/mongoid/middleware/identity_map.rb:33:in `block in call'
  mongoid (3.0.6) lib/mongoid/unit_of_work.rb:39:in `unit_of_work'
  mongoid (3.0.6) lib/rack/mongoid/middleware/identity_map.rb:33:in `call'
  warden (1.2.1) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.1) lib/warden/manager.rb:34:in `catch'
  warden (1.2.1) lib/warden/manager.rb:34:in `call'
  rack (1.4.1) lib/rack/etag.rb:23:in `call'
  rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in `_run__93877302595973219__call__1631561807570460414__callbacks'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.8) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.8) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.8) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.8) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/static.rb:62:in `call'
  railties (3.2.8) lib/rails/engine.rb:479:in `call'
  railties (3.2.8) lib/rails/application.rb:223:in `call'
  rack (1.4.1) lib/rack/content_length.rb:14:in `call'
  railties (3.2.8) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.1) lib/rack/handler/webrick.rb:59:in `service'
  /Users/nicholaswyoung/.rvm/rubies/ruby-1.9.3-p194-dev/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
  /Users/nicholaswyoung/.rvm/rubies/ruby-1.9.3-p194-dev/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /Users/nicholaswyoung/.rvm/rubies/ruby-1.9.3-p194-dev/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'


  Rendered /Users/nicholaswyoung/.rvm/gems/ruby-1.9.3-p194-dev/gems/actionpack-3.2.8/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.1ms)
  Rendered /Users/nicholaswyoung/.rvm/gems/ruby-1.9.3-p194-dev/gems/actionpack-3.2.8/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (0.9ms)
  Rendered /Users/nicholaswyoung/.rvm/gems/ruby-1.9.3-p194-dev/gems/actionpack-3.2.8/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (8.2ms)
```

**Comment by gregglowrimore** [comment]
I'm getting this same undefined method '[]' for nil::NilClass when trying to use the Rally service hook in GitHub Enterprise 2.1.2, /data/hookshot/current/vendor/gems/ruby/2.1.0/gems/github-services-1.0.0.05205ac/lib/services/rally.rb:119

**Comment by ecauli** [comment]
any way to solve this problem?

**Comment by xjunior** [comment]
@ecauli see my comkment from May 29, 2013
