### ISSUE TITLE
undefined method `generate_token`

### ISSUE THREAD

**Issue by guilhermesimoes** [plataformatec/devise#2580]
I followed [the TL;DR for upgrading Devise](http://blog.plataformatec.com.br/2013/08/devise-3-1-now-with-more-secure-defaults/) and here's where I stand:

``` ruby
gem 'rails', '~> 3.2.13'
gem 'devise', '~> 3.1.0.rc2'
```

However, when logging in with email and password, I get the following:

```
NoMethodError - undefined method `generate_token' for #<Class:0x5665b60>:
  activerecord (3.2.13) lib/active_record/dynamic_matchers.rb:55:in `method_missing'
  devise (3.1.0.rc2) lib/devise/models/rememberable.rb:118:in `remember_token'
  devise (3.1.0.rc2) lib/devise/models/rememberable.rb:51:in `remember_me!'
  devise (3.1.0.rc2) lib/devise/controllers/rememberable.rb:26:in `remember_me'
  devise (3.1.0.rc2) lib/devise/hooks/rememberable.rb:5:in `block in <top (required)>'
...
```

If I uncheck the `remember_me` checkbox it works. What did I miss when upgrading to the new Devise version?

**Comment by agm1988** [comment]
still having this issue in 3.5.10
