### ISSUE TITLE
ActionController::UnknownFormat in Devise::RegistrationsController#new

### ISSUE THREAD

**Issue by zeeshanmmalik** [plataformatec/devise#2667]
Rails 4.0.0, Devise 3.1.1, Warden 1.2.3

Upon clicking /users/sign_up.user link I get following exception:

```
Started GET "/users/sign_up.user" for 127.0.0.1 at 2013-10-04 21:58:39 -0400
Processing by Devise::RegistrationsController#new as 
Completed 406 Not Acceptable in 1ms

ActionController::UnknownFormat (ActionController::UnknownFormat):
  actionpack (4.0.0) lib/action_controller/metal/mime_responds.rb:372:in `retrieve_collector_from_mimes'
  actionpack (4.0.0) lib/action_controller/metal/mime_responds.rb:327:in `respond_with'
  devise (3.1.1) app/controllers/devise/registrations_controller.rb:8:in `new'
  actionpack (4.0.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.0.0) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.0.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.0.0) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (4.0.0) lib/active_support/callbacks.rb:413:in `_run__890637270__process_action__callbacks'
  activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.0) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (4.0.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.0.0) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.0) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.0.0) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  activerecord (4.0.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.0.0) lib/abstract_controller/base.rb:136:in `process'
  actionpack (4.0.0) lib/abstract_controller/rendering.rb:44:in `process'
  actionpack (4.0.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.0.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.0.0) lib/action_controller/metal.rb:231:in `block in action'
  actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:80:in `call'
  actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:48:in `call'
  actionpack (4.0.0) lib/action_dispatch/routing/mapper.rb:44:in `call'
  actionpack (4.0.0) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.0) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.0.0) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:655:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/flash.rb:241:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/cookies.rb:486:in `call'
  activerecord (4.0.0) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.0.0) lib/active_support/callbacks.rb:373:in `_run__594484681__call__callbacks'
  activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/reloader.rb:64:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.0) lib/rails/rack/logger.rb:21:in `block in call'
  activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `block in tagged'
  activesupport (4.0.0) lib/active_support/tagged_logging.rb:25:in `tagged'
  activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `tagged'
  railties (4.0.0) lib/rails/rack/logger.rb:21:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.0) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/static.rb:64:in `call'
  railties (4.0.0) lib/rails/engine.rb:511:in `call'
  railties (4.0.0) lib/rails/application.rb:97:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
  /home/rehan/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
  /home/rehan/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /home/rehan/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

```

I was initially using Devise 3.0.0.rc when I got this exception, then I upgraded devise to 3.1.1 but the exception did not go away.

**Comment by yalab** [comment]
#include <iostream>
#include "editor-support/cocostudio/FlatBuffersSerialize.h"
#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>

using namespace std;

cocostudio::FlatBuffersSerialize fbs;

void serialize(const std::string root, const std::string input)
{
  char buf[255];
  getcwd(buf,255);
  std::string curdir(buf);
  mkdir((curdir + "/output").c_str(), 0755);
  std::string output = curdir + "/output" + input.substr(root.size());
  printf("Process: %s \n", output.c_str());
  std::string dirname =  output.substr(0, output.find_last_of('/'));
  mkdir(dirname.c_str(), 0755);
  fbs.serializeFlatBuffersWithXMLFile(input, output);
}

void processDir(const std::string root, const std::string& dirname)
{
  DIR *dir;
  struct dirent *ent;
  if((dir = opendir(dirname.c_str())) == NULL){
    return;
  }
  while((ent = readdir(dir)) != NULL){
    string fname = ent->d_name;

    switch(ent->d_type){
    case DT_DIR: {
      if      (fname == "."){
        continue;
      }else if(fname == ".."){
        continue;
      }
      stringstream buf;
      buf << dirname;
      buf << "/";
      buf << fname;
      processDir(root, buf.str().c_str());
      continue;
    }
    case DT_REG: {
      string extname = fname.substr(fname.find_last_of('.'));
      if(extname == ".csd"){
        serialize(root, dirname + "/" +fname);
      }
      continue;
    }
    }
  }
  closedir(dir);
}

int main(int argc, char *argv[])
{
  if(argc < 2){
    cout << "USAGE: " ;
    cout << argv[0];
    cout << " COCOSTUDIO_DIR";
    return -1;
  }
  
  auto root = argv[1];
  processDir(root, root);
}

**Comment by eseca** [comment]
I'm getting the same UnknownFormat for `<user_model>_password_path`. I agree, the problem is not the rise of the error but that dot and something at the end of the path. `edit_<user_model>_password_path` does it too. I fixed it by removing from the point to the end of the string:
```
showman_password_path(resource_name).sub(/\.[\w]*\z/, '')
```
In my `password/edit.html.erb`.

**Comment by Pete-Tyldesley** [comment]
@eseca Thank you so much for that! You have saved me so much time. Can't believe I didn't think of that. I have been racking my brains for hours!

**Comment by TangMonk** [comment]
same problem in devise 4.2, the url is `http://localhost:3000/users/confirmation.user`

**Comment by dlo** [comment]
@thejamespinto hint worked perfectly for me, thanks!

**Comment by saluminati** [comment]
> I encountered the problem on password reset request: views/devise/passwords/new.html.haml
> 
> The problem was solved substituting `user_password_path(resource_name)` with `user_password_path()`
> 
> PD: my resource was name is "user"

your solution worked for me. You bloody champ
