### ISSUE TITLE
Error during failsafe response: uncaught throw :warden

### ISSUE THREAD

**Issue by christian-froh** [plataformatec/devise#2719]
I just tried to rebuild dynamic exception handling from Ryan Bates http://railscasts.com/episodes/53-handling-exceptions-revised

If I'm logged in and produce some errors like routing errors, then everything seems to be fine. If I'm not logged in and produce this routing error again then I get this weird error:

```
Error during failsafe response: uncaught throw :warden
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/warden-1.2.3/lib/warden/proxy.rb:128:in `throw'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/warden-1.2.3/lib/warden/proxy.rb:128:in `authenticate!'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/devise-3.0.3/lib/devise/controllers/helpers.rb:48:in `authenticate_user!'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:451:in `_run__1574333390992446689__process_action__2922189031216360973__callbacks'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:17:in `process_action'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/newrelic_rpm-3.6.7.159/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:38:in `block in process_action'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/newrelic_rpm-3.6.7.159/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:324:in `perform_action_with_newrelic_trace'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/newrelic_rpm-3.6.7.159/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:37:in `process_action'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/abstract_controller/base.rb:121:in `process'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:45:in `process'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_controller/metal.rb:203:in `dispatch'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_controller/metal.rb:246:in `block in action'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:36:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:608:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_dispatch/middleware/show_exceptions.rb:76:in `render_exception'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_dispatch/middleware/show_exceptions.rb:61:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/railties-3.2.14/lib/rails/rack/logger.rb:32:in `call_app'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `block in call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/activesupport-3.2.14/lib/active_support/tagged_logging.rb:22:in `tagged'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/railties-3.2.14/lib/rails/rack/logger.rb:16:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/activesupport-3.2.14/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/actionpack-3.2.14/lib/action_dispatch/middleware/static.rb:63:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/railties-3.2.14/lib/rails/engine.rb:484:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/railties-3.2.14/lib/rails/application.rb:231:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/railties-3.2.14/lib/rails/rack/log_tailer.rb:17:in `call'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/rack-1.4.5/lib/rack/handler/thin.rb:13:in `run'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/rack-1.4.5/lib/rack/server.rb:268:in `start'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/railties-3.2.14/lib/rails/commands/server.rb:70:in `start'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/railties-3.2.14/lib/rails/commands.rb:55:in `block in <top (required)>'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/railties-3.2.14/lib/rails/commands.rb:50:in `tap'
  /home/christian/.rvm/gems/ruby-2.0.0-p0@travel/gems/railties-3.2.14/lib/rails/commands.rb:50:in `<top (required)>'
  script/rails:23:in `require'
  script/rails:23:in `<main>'
```

Anyone an idea?

**Comment by pcragone** [comment]
Hi there -

I'm getting this same error.  Do you have any suggestions to point me in the right direction?

**Comment by cbezares** [comment]
Same error here, only happens when app runs in production environment.

**Comment by abdulhanan-fauree** [comment]
Same error here, only happens when app runs in production environment.
