### ISSUE TITLE
BCrypt::Errors::InvalidCost on 3.2.0

### ISSUE THREAD

**Issue by masterkain** [plataformatec/devise#2724]
Hello,
I upgraded to 3.2.0 from 3.1.1, in my specs I get this exception when trying to create a user:

```
Failure/Error: post :create, user: @params
  BCrypt::Errors::InvalidCost:
    cost must be numeric and > 0

~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/bcrypt-ruby-3.1.2/lib/bcrypt/engine.rb:79:in `generate_salt'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/bcrypt-ruby-3.1.2/lib/bcrypt/password.rb:46:in `create'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/devise-3.2.0/lib/devise/models/database_authenticatable.rb:7:in `bcrypt'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/devise-3.2.0/lib/devise/models/database_authenticatable.rb:42:in `password='
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activerecord-4.0.1/lib/active_record/attribute_assignment.rb:42:in `public_send'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activerecord-4.0.1/lib/active_record/attribute_assignment.rb:42:in `_assign_attribute'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activerecord-4.0.1/lib/active_record/attribute_assignment.rb:29:in `block in assign_attributes'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activerecord-4.0.1/lib/active_record/attribute_assignment.rb:23:in `each'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activerecord-4.0.1/lib/active_record/attribute_assignment.rb:23:in `assign_attributes'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activerecord-4.0.1/lib/active_record/core.rb:460:in `init_attributes'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activerecord-4.0.1/lib/active_record/core.rb:185:in `initialize'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/devise-3.2.0/lib/devise/models/confirmable.rb:47:in `initialize'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activerecord-4.0.1/lib/active_record/inheritance.rb:27:in `new'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activerecord-4.0.1/lib/active_record/inheritance.rb:27:in `new'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/devise-3.2.0/lib/devise/models/registerable.rb:20:in `new_with_session'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/devise-3.2.0/app/controllers/devise/registrations_controller.rb:92:in `build_resource'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/devise-3.2.0/app/controllers/devise/registrations_controller.rb:13:in `create'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/actionpack-4.0.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/actionpack-4.0.1/lib/abstract_controller/base.rb:189:in `process_action'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/actionpack-4.0.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/actionpack-4.0.1/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activesupport-4.0.1/lib/active_support/callbacks.rb:423:in `_run__1941475485630819418__process_action__callbacks'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activesupport-4.0.1/lib/active_support/callbacks.rb:80:in `run_callbacks'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/actionpack-4.0.1/lib/abstract_controller/callbacks.rb:17:in `process_action'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/actionpack-4.0.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/actionpack-4.0.1/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activesupport-4.0.1/lib/active_support/notifications.rb:159:in `block in instrument'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activesupport-4.0.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activesupport-4.0.1/lib/active_support/notifications.rb:159:in `instrument'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/actionpack-4.0.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/actionpack-4.0.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/activerecord-4.0.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/actionpack-4.0.1/lib/abstract_controller/base.rb:136:in `process'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/actionpack-4.0.1/lib/abstract_controller/rendering.rb:44:in `process'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/actionpack-4.0.1/lib/action_controller/test_case.rb:569:in `process'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/actionpack-4.0.1/lib/action_controller/test_case.rb:64:in `process'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/devise-3.2.0/lib/devise/test_helpers.rb:19:in `block in process'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/devise-3.2.0/lib/devise/test_helpers.rb:72:in `catch'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/devise-3.2.0/lib/devise/test_helpers.rb:72:in `_catch_warden'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/devise-3.2.0/lib/devise/test_helpers.rb:19:in `process'
~/.rvm/gems/ruby-2.1.0-preview1@myapp/gems/actionpack-4.0.1/lib/action_controller/test_case.rb:475:in `post'
./spec/controllers/users/registrations_controller_spec.rb:83:in `block (3 levels) in <top (required)>'
```

I have not yet tried with `ruby-2.0.0-p247`.

**Comment by prpetten** [comment]
Thank you @masterkain !  I was having the same issue
