### ISSUE TITLE
if secret_token isnt set Devise.token_generator returns nil

### ISSUE THREAD

**Issue by awsmsrc** [plataformatec/devise#3027]
this causes an undefined method generate for nil class error, which is tricky to track down.

Happy to help out if I can, didnt want to write any code if there was a good reason for this!

**Comment by gnapse** [comment]
I have a similar situation. My app boots ok, it has the `secret_key_base` set in the `config/secrets.yml` file (if that's what you guys mean above), and still I get the `Devise.token_generator == nil` situation, which prevents me to use Devise's confirmable module. The only thing I can note in common with @awsmsrc is that my app is also a [rails-api](https://github.com/rails-api/rails-api) app. I suspect this may have something to do with this issue.

**Comment by gnapse** [comment]
I've created a sample project where this is happening, if someone's willing to investigate http://cl.ly/003o1m292B2l

After unzipping just `rake db:setup` and then `bundle exec rails c`. Then on the console issue the following command:

```ruby
user = User.create(name: 'John Doe', email: 'john.doe@example.com', password: '12345678', password_confirmation: '12345678')
```

This is the output I get:

```ruby
$ bundle exec rails c
Loading development environment (Rails 4.2.0)
>> user = User.create(name: 'John Doe', email: 'john.doe@example.com', password: '12345678', password_confirmation: '12345678')
   (0.1ms)  begin transaction
  User Exists (0.2ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = 'john.doe@example.com' LIMIT 1
  User Exists (0.1ms)  SELECT  1 AS one FROM "users" WHERE "users"."name" = 'John Doe' LIMIT 1
   (0.1ms)  rollback transaction
NoMethodError: undefined method `generate' for nil:NilClass
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/models/confirmable.rb:221:in `generate_confirmation_token'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:427:in `block in make_lambda'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:145:in `call'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `call'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_create_callbacks'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/callbacks.rb:306:in `_create_record'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/timestamp.rb:57:in `_create_record'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/persistence.rb:501:in `create_or_update'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/callbacks.rb:302:in `block in create_or_update'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
... 10 levels...
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:286:in `block in save'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:285:in `save'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/persistence.rb:34:in `create'
	from (irb):1
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'>>
```

**Comment by gnapse** [comment]
Forget about it. Foreman's dotenv was not loading my environment variables because of a misconfiguration, and there's where I have the secret key. Sorry.
