### ISSUE TITLE
Rails 4.2.0beta1 : undefined method `merge!' for #<ActionDispatch::Routing::Mapper::Scope:0x007fe4b8dfd7f8>

### ISSUE THREAD

**Issue by aantix** [plataformatec/devise#3158]
Updated Rails to 4.2.0.beta1.  Received the following stack trace when launching `rails s` : 

```
/Users/aantix/.rvm/gems/ruby-2.1.1/gems/devise-3.3.0/lib/devise/rails/routes.rb:457:in `ensure in with_devise_exclusive_scope': undefined method `merge!' for #<ActionDispatch::Routing::Mapper::Scope:0x007fe4b8dfd7f8> (NoMethodError)
    from /Users/aantix/.rvm/gems/ruby-2.1.1/gems/devise-3.3.0/lib/devise/rails/routes.rb:457:in `with_devise_exclusive_scope'
    from /Users/aantix/.rvm/gems/ruby-2.1.1/gems/devise-3.3.0/lib/devise/rails/routes.rb:248:in `block (2 levels) in devise_for'
    from /Users/aantix/.rvm/gems/ruby-2.1.1/gems/devise-3.3.0/lib/devise/rails/routes.rb:351:in `block in devise_scope'
    from /Users/aantix/.rvm/gems/ruby-2.1.1/gems/actionpack-4.2.0.beta1/lib/action_dispatch/routing/mapper.rb:932:in `block in constraints'
    from /Users/aantix/.rvm/gems/ruby-2.1.1/gems/actionpack-4.2.0.beta1/lib/action_dispatch/routing/mapper.rb:808:in `scope'
    from /Users/aantix/.rvm/gems/ruby-2.1.1/gems/actionpack-4.2.0.beta1/lib/action_dispatch/routing/mapper.rb:932:in `constraints'
    from /Users/aantix/.rvm/gems/ruby-2.1.1/gems/devise-3.3.0/lib/devise/rails/routes.rb:350:in `devise_scope'
    from /Users/aantix/.rvm/gems/ruby-2.1.1/gems/devise-3.3.0/lib/devise/rails/routes.rb:247:in `block in devise_for'
    from /Users/aantix/.rvm/gems/ruby-2.1.1/gems/devise-3.3.0/lib/devise/rails/routes.rb:223:in `each'
    from /Users/aantix/.rvm/gems/ruby-2.1.1/gems/devise-3.3.0/lib/devise/rails/routes.rb:223:in `devise_for'
    from /Users/aantix/dev/followup/config/routes.rb:6:in `block in <top (required)>'
```

Here's the offending line in my routes file.

```
devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
```

Still need to investigate this.

**Comment by amritdeep** [comment]
You can use devise 3.4.1.
