### ISSUE TITLE
Still getting "undefined method `merge!'" with Rails 4.2 and Devise 3.4

### ISSUE THREAD

**Issue by Zensavona** [plataformatec/devise#3454]
I've had a look online and it seemed that this issue was solved with Devise 3.4.0? I'm still getting this error with the latest version of Devise and Rails 4.2, here's the error and a stack trace:

The error is thrown for the line in my `routes.rb` which contains `devise_for :users`.

````
undefined method `merge!' for #<ActionDispatch::Routing::Mapper::Scope:0x007f9ab9338c80>
````

And a stack trace:

````
devise (3.2.4) lib/devise/rails/routes.rb:455:in `ensure in with_devise_exclusive_scope'
devise (3.2.4) lib/devise/rails/routes.rb:455:in `with_devise_exclusive_scope'
devise (3.2.4) lib/devise/rails/routes.rb:246:in `block (2 levels) in devise_for'
devise (3.2.4) lib/devise/rails/routes.rb:349:in `block in devise_scope'
actionpack (4.2.0) lib/action_dispatch/routing/mapper.rb:940:in `block in constraints'
actionpack (4.2.0) lib/action_dispatch/routing/mapper.rb:816:in `scope'
actionpack (4.2.0) lib/action_dispatch/routing/mapper.rb:940:in `constraints'
devise (3.2.4) lib/devise/rails/routes.rb:348:in `devise_scope'
devise (3.2.4) lib/devise/rails/routes.rb:245:in `block in devise_for'
devise (3.2.4) lib/devise/rails/routes.rb:220:in `each'
devise (3.2.4) lib/devise/rails/routes.rb:220:in `devise_for'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:423:in `instance_exec'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:423:in `eval_block'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:401:in `draw'
activesupport (4.2.0) lib/active_support/dependencies.rb:268:in `load'
activesupport (4.2.0) lib/active_support/dependencies.rb:268:in `block in load'
activesupport (4.2.0) lib/active_support/dependencies.rb:240:in `load_dependency'
activesupport (4.2.0) lib/active_support/dependencies.rb:268:in `load'
railties (4.2.0) lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
railties (4.2.0) lib/rails/application/routes_reloader.rb:40:in `each'
railties (4.2.0) lib/rails/application/routes_reloader.rb:40:in `load_paths'
railties (4.2.0) lib/rails/application/routes_reloader.rb:16:in `reload!'
railties (4.2.0) lib/rails/application/routes_reloader.rb:26:in `block in updater'
activesupport (4.2.0) lib/active_support/file_update_checker.rb:75:in `call'
activesupport (4.2.0) lib/active_support/file_update_checker.rb:75:in `execute'
railties (4.2.0) lib/rails/application/routes_reloader.rb:7:in `execute'
railties (4.2.0) lib/rails/application/finisher.rb:81:in `block (2 levels) in <module:Finisher>'
activesupport (4.2.0) lib/active_support/callbacks.rb:441:in `instance_exec'
activesupport (4.2.0) lib/active_support/callbacks.rb:441:in `block in make_lambda'
activesupport (4.2.0) lib/active_support/callbacks.rb:189:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:189:in `block in simple'
activesupport (4.2.0) lib/active_support/callbacks.rb:190:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:190:in `block in simple'
activesupport (4.2.0) lib/active_support/callbacks.rb:190:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:190:in `block in simple'
activesupport (4.2.0) lib/active_support/callbacks.rb:190:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:190:in `block in simple'
activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_prepare_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:71:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:18:in `middleware_call'
web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.0) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.0) lib/rack/lock.rb:17:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
railties (4.2.0) lib/rails/engine.rb:518:in `call'
railties (4.2.0) lib/rails/application.rb:164:in `call'
rack (1.6.0) lib/rack/lock.rb:17:in `call'
rack (1.6.0) lib/rack/content_length.rb:15:in `call'
rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
````

Also FWIW I can make the error go away by commenting out `devise_for :users` from `routes.rb`, but I'm not exactly sure what impact this has on the application.

Any help would be greatly appreciated :+1:

**Comment by lucasmazza** [comment]
Can you provide a sample app that replicates the error?

**Comment by Zensavona** [comment]
My bad, i didn't have a root defined in my routes.rb

**Comment by aashish** [comment]
I have the same issue. This problem occurred while upgrading from rails '4.0.0' to rails '4.2.0' with devise gem version at '3.1.2'. The problem goes away if i comment ```devise_for :users``` from ```routes.rb```.

**Comment by carlosantoniodasilva** [comment]
@aashish upgrade devise to at least v3.4.0, it's the version that got compatibility with Rails 4.2. Please check the changelog for more information.

**Comment by aashish** [comment]
thanks, It resolved the issue.

**Comment by ziaulrehman40** [comment]
Getting similar error on latest devise on rails 6.0.1

```
INFO -- : Started GET "/admin/sign_in" for 116.0.54.66 at 2019-11-29 09:49:15 +0000
INFO -- : Processing by Devise::SessionsController#new as HTML
INFO -- :   Rendering /home/.../shared/bundle/ruby/2.6.0/gems/devise-4.7.1/app/views/devise/sessions/new.html.erb within layouts/application
INFO -- :   Rendered /home/.../shared/bundle/ruby/2.6.0/gems/devise-4.7.1/app/views/devise/sessions/new.html.erb within layouts/application (Duration: 0.9ms | Allocations: 551)
INFO -- : Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms | Allocations: 1249)
FATAL -- :   
ActionView::Template::Error (undefined method `merge' for nil:NilClass):
    1: <h2>Log in</h2>
    2: 
    3: <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    4:   <div class="field">
    5:     <%= f.label :email %><br />
    6:     <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  
actionpack (6.0.1) lib/action_dispatch/routing/route_set.rb:798:in `url_for'
actionpack (6.0.1) lib/action_dispatch/routing/route_set.rb:272:in `call'
actionpack (6.0.1) lib/action_dispatch/routing/route_set.rb:213:in `call'
actionpack (6.0.1) lib/action_dispatch/routing/route_set.rb:329:in `block in define_url_helper'
actionpack (6.0.1) lib/action_dispatch/routing/routes_proxy.rb:45:in `admin_session_path'
devise (4.7.1) lib/devise/controllers/url_helpers.rb:53:in `block (4 levels) in generate_helpers!'
devise (4.7.1) app/views/devise/sessions/new.html.erb:3
actionview (6.0.1) lib/action_view/base.rb:274:in `_run'
actionview (6.0.1) lib/action_view/template.rb:185:in `block in render'
activesupport (6.0.1) lib/active_support/notifications.rb:182:in `instrument'
actionview (6.0.1) lib/action_view/template.rb:386:in `instrument_render_template'
actionview (6.0.1) lib/action_view/template.rb:183:in `render'
actionview (6.0.1) lib/action_view/renderer/template_renderer.rb:59:in `block (2 levels) in render_template'
actionview (6.0.1) lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
activesupport (6.0.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.1) lib/active_support/notifications.rb:180:in `instrument'
actionview (6.0.1) lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
actionview (6.0.1) lib/action_view/renderer/template_renderer.rb:58:in `block in render_template'
actionview (6.0.1) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
actionview (6.0.1) lib/action_view/renderer/template_renderer.rb:57:in `render_template'
actionview (6.0.1) lib/action_view/renderer/template_renderer.rb:13:in `render'
actionview (6.0.1) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (6.0.1) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (6.0.1) lib/action_view/rendering.rb:118:in `block in _render_template'
actionview (6.0.1) lib/action_view/base.rb:304:in `in_rendering_context'
actionview (6.0.1) lib/action_view/rendering.rb:117:in `_render_template'
actionpack (6.0.1) lib/action_controller/metal/streaming.rb:219:in `_render_template'
actionview (6.0.1) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (6.0.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (6.0.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (6.0.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (6.0.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (6.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (6.0.1) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/home/deployer/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
activesupport (6.0.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (6.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (6.0.1) lib/action_controller/metal/instrumentation.rb:85:in `cleanup_view_runtime'
activerecord (6.0.1) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (6.0.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
wicked_pdf (1.4.0) lib/wicked_pdf/pdf_helper.rb:46:in `call'
wicked_pdf (1.4.0) lib/wicked_pdf/pdf_helper.rb:46:in `render_with_wicked_pdf'
wicked_pdf (1.4.0) lib/wicked_pdf/pdf_helper.rb:30:in `render'
responders (3.0.0) lib/action_controller/responder.rb:240:in `default_render'
responders (3.0.0) lib/action_controller/responder.rb:172:in `to_html'
responders (3.0.0) lib/action_controller/responder.rb:165:in `respond'
responders (3.0.0) lib/action_controller/responder.rb:158:in `call'
responders (3.0.0) lib/action_controller/respond_with.rb:213:in `respond_with'
devise (4.7.1) app/controllers/devise/sessions_controller.rb:14:in `new'
actionpack (6.0.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.1) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.1) lib/active_support/callbacks.rb:112:in `block in run_callbacks'
react-rails (2.6.0) lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
activesupport (6.0.1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
activesupport (6.0.1) lib/active_support/callbacks.rb:139:in `run_callbacks'
actionpack (6.0.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.1) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.1) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.1) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.1) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
actionpack (6.0.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.1) lib/action_dispatch/routing/route_set.rb:837:in `call'
omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/builder.rb:64:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (6.0.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (6.0.1) lib/action_dispatch/middleware/cookies.rb:648:in `call'
actionpack (6.0.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.1) lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
railties (6.0.1) lib/rails/engine.rb:526:in `call'
puma (4.3.0) lib/puma/configuration.rb:228:in `call'
puma (4.3.0) lib/puma/server.rb:667:in `handle_request'
puma (4.3.0) lib/puma/server.rb:470:in `process_client'
puma (4.3.0) lib/puma/server.rb:328:in `block in run'
puma (4.3.0) lib/puma/thread_pool.rb:134:in `block in spawn_thread'

```
