### ISSUE TITLE
[Error] devise 3.4.1 URI::InvalidURIError (the scheme http does not accept registry part: app_server (or bad hostname?))

### ISSUE THREAD

**Issue by leandromoreira** [plataformatec/devise#3464]
I was able to login as FB before but now it raises this error, is this specific for 3.4.1? I double checked my FB apps (domain name and site url) all with https. Have any of you faced this error?

````
Started GET "/users/auth/facebook" for x.x.x.x at 2015-02-12 00:45:05 +0000
Started GET "/users/auth/facebook/callback?code=xxxx" for 127.0.0.1 at 2015-02-12 00:45:05 +0000

URI::InvalidURIError (the scheme http does not accept registry part: app_server (or bad hostname?)):
  /home/deployer/.rbenv/versions/2.0.0-p195/lib/ruby/2.0.0/uri/generic.rb:214:in `initialize'
  /home/deployer/.rbenv/versions/2.0.0-p195/lib/ruby/2.0.0/uri/http.rb:84:in `initialize'
  /home/deployer/.rbenv/versions/2.0.0-p195/lib/ruby/2.0.0/uri/common.rb:214:in `new'
  /home/deployer/.rbenv/versions/2.0.0-p195/lib/ruby/2.0.0/uri/common.rb:214:in `parse'
  /home/deployer/.rbenv/versions/2.0.0-p195/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
  omniauth (1.2.2) lib/omniauth/strategy.rb:416:in `full_host'
````

**Comment by josevalim** [comment]
We haven't changed anything in this area. Did you upgrade only Devise or other gems too? If so, that's where I would look.

**Comment by leandromoreira** [comment]
Thanks @josevalim, it turns out that it was an issue with nginx, I forgot to forward the host header for a given location. I just set the header host for my proxy. (I had to dig deeper to come to this conclusion)

`proxy_set_header Host 'example.com';`
