### ISSUE TITLE
devise migration of existing table throws 'undefined method `recoverable`'

### ISSUE THREAD

**Issue by TonnyXu** [plataformatec/devise#3487]
I added the devise support to an existing table `user` just by following the wiki page: [How To: Change an already existing table to add devise required columns](https://github.com/plataformatec/devise/wiki/How-To:-Change-an-already-existing-table-to-add-devise-required-columns). 

It worked fine in my previous version with devise 3.2.3 + rails 4.0.0.

Today, I upgraded the rails to 4.2.0, also upgraded devise to 3.4.1, now when I do a migration on a new machine, it reports like this:

```
== 20140201122431 DeviseCreateUsers: migrating ================================
-- change_table(:users)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `recoverable' for #<ActiveRecord::ConnectionAdapters::Table:0x007fe63e3c36c0>/xxxx/db/migrate/20140201122431_devise_create_users.rb:4:in `block in up'
/xxxx/db/migrate/20140201122431_devise_create_users.rb:3:in `up'
NoMethodError: undefined method `recoverable' for #<ActiveRecord::ConnectionAdapters::Table:0x007fe63e3c36c0>
/xxxx/db/migrate/20140201122431_devise_create_users.rb:4:in `block in up'
/xxxx/db/migrate/20140201122431_devise_create_users.rb:3:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

##### inside the migration file

```
class DeviseCreateUsers < ActiveRecord::Migration
  def self.up
    change_table(:users) do |t|
      t.recoverable
      t.rememberable
      t.trackable
      t.string    "encrypted_password", :null => false
      t.string    "password_salt"
    end

    # t.encryptable
    # t.confirmable
    # t.lockable :lock_strategy => :failed_attempts, :unlock_strategy => :both
    # t.token_authenticatable



    add_index :users, :email,                :unique => true
    add_index :users, :reset_password_token, :unique => true
    # add_index :users, :confirmation_token,   :unique => true
    # add_index :users, :unlock_token,         :unique => true
    # add_index :users, :authentication_token, :unique => true
  end

  def self.down
    remove_column :users, :recoverable
    remove_column :users, :rememberable
    remove_column :users, :trackeable
    remove_column :users, :encrypted_password
    remove_column :users, :password_salt
  end
end
```

I upgraded rails by changing the Gemfile, followed by `bundle update` and `rake rails:update`. In the Gemfile, I updated devise to 3.4.1. 

Can anyone tell me how to handle this?

**Comment by josevalim** [comment]
That file is using the old style syntax that has long ago been removed. You need to upgrade your migration accordingly: https://github.com/plataformatec/devise/wiki/How-To:-Upgrade-to-Devise-2.0-migration-schema-style

**Comment by TonnyXu** [comment]
@josevalim Thanks! that works!
