### ISSUE TITLE
undefined method `token_authentication_key=' for Devise:Module (NoMethodError)

### ISSUE THREAD

**Issue by andricicezar** [plataformatec/devise#3620]
I have updated to 3.5.1 from 3.4.1 and now I get this error:

```
.../config/initializers/devise.rb:199:in `block in <top (required)>': undefined method `token_authentication_key=' for Devise:Module (NoMethodError)
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/devise-3.5.1/lib/devise.rb:281:in `setup'
	from .../config/initializers/devise.rb:3:in `<top (required)>'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:166:in `instrument'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/engine.rb:651:in `load_config_initializer'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/engine.rb:615:in `each'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/cezar/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /home/cezar/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/cezar/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/cezar/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /home/cezar/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `each'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /home/cezar/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:411:in `call'
	from /home/cezar/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
	from /home/cezar/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/cezar/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /home/cezar/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /home/cezar/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/cezar/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /home/cezar/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `public_send'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `method_missing'
	from .../config/environment.rb:5:in `<top (required)>'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from .../config.ru:3:in `block in <main>'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/rack-1.6.1/lib/rack/builder.rb:55:in `instance_eval'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/rack-1.6.1/lib/rack/builder.rb:55:in `initialize'
	from .../config.ru:in `new'
	from .../config.ru:in `<main>'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/rack-1.6.1/lib/rack/builder.rb:49:in `eval'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/rack-1.6.1/lib/rack/builder.rb:49:in `new_from_string'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/rack-1.6.1/lib/rack/builder.rb:40:in `parse_file'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/rack-1.6.1/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/rack-1.6.1/lib/rack/server.rb:208:in `app'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/commands/server.rb:61:in `app'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/rack-1.6.1/lib/rack/server.rb:336:in `wrapped_app'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/commands/server.rb:78:in `start'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/cezar/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

**Comment by carlosantoniodasilva** [comment]
These methods have been deprecated for a long time, and were removed in d1d5996b6b107e59baa486f11209ca25d4f4a998. You can just get rid of them from your initializer. Thanks!
