### ISSUE TITLE
Devise has issues with csrf meta tags in partial

### ISSUE THREAD

**Issue by krainboltgreene** [plataformatec/devise#3625]
1. Create project (krainboltgreene/partial_secure_token_meta_tag@dfc627060be2a99641e47f05dff191c23994500b)
  1. Run: `rails new partial_secure_token_meta_tag --skip-bundle --skip-test-unit`
2. Move the `<%= csrf_meta_tags %>` from `app/views/layouts/application.html.erb` to `app/views/application/_meta.html.erb` (krainboltgreene/partial_secure_token_meta_tag@668cac63770b869624b9eacc8bed98006c72257c)
  1. Run: `mkdir app/views/application`
  2. Run: `touch app/views/application/_meta.html.erb`
  3. Cut `<%= csrf_meta_tags %>` from 1 and into 2
4. Add `devise`, version 3.5.1 (krainboltgreene/partial_secure_token_meta_tag@8529aecaadc97b27d1e4ae080e22f60ddbcf091d)
5. Running `bin/rails generate devise:install` (krainboltgreene/partial_secure_token_meta_tag@8954e8d7ea232f1c075273b4260946e87f056b7c)
6. Create a new devise model called `Account` (krainboltgreene/partial_secure_token_meta_tag@a6c47caf54e9d698e3338bab2bbf6eaec08cfaec)
  1. Run: `bin/rails generate devise account`
  2. Run: `bin/rake db:create db:migrate`
7. Create devise controllers (krainboltgreene/partial_secure_token_meta_tag@95b2953803adc89a8e51a6a0215f646fea1d5021)
  1. Run: `bin/rails generate devise:controllers accounts`
  2. Change `config/routes.rb`, see commit
8. Create a dashboard page (krainboltgreene/partial_secure_token_meta_tag@fa336a9f9ee69ef8632bf398529469b68a874b75)
  1. Run: `bin/rails generate controller pages dashboard`
9. Add signin/signout/signup links to the dashboard page (krainboltgreene/partial_secure_token_meta_tag@09b3d5b59c9699519dc7013b22da6611b9a3298f)
  1. Change `app/views/pages/dashboard.html.erb`, see commit
10. Make the dashboard page root (krainboltgreene/partial_secure_token_meta_tag@bb8f1061ab54dc3868816426ec9738ad8ba8a218)
  1. Change `config/routes.rb`, see commit
11. Start the server
  1. Run: `bin/rails server`
12. Sign in
  1. Go to: `http://localhost:3000/`
  2. Click `Sign in`
  3. Enter email: `kurtis@example.com`
  4. Enter password: `12341234`
  5. Enter password confiramtion: `12341234`
  6. Click Sign Up
13. Sign out
  1. Click `Sign out`
  
    ```
    Started DELETE "/accounts/sign_out" for ::1 at 2015-06-07 18:10:42 -0500
    Processing by Accounts::SessionsController@destroy as HTML
      Account Load (0.1ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = ?  ORDER BY "accounts"."id" ASC LIMIT 1  [["id", 1]]
    Can't verify CSRF token authenticity
    Completed 422 Unprocessable Entity in 5ms (ActiveRecord: 0.1ms)

    ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
    actionpack (4.2.1) lib/action_controller/metal/request_forgery_protection.rb:181:in `handle_unverified_request'
    actionpack (4.2.1) lib/action_controller/metal/request_forgery_protection.rb:209:in `handle_unverified_request'
    devise (3.5.1) lib/devise/controllers/helpers.rb:251:in `handle_unverified_request'
    actionpack (4.2.1) lib/action_controller/metal/request_forgery_protection.rb:204:in `verify_authenticity_token'
    activesupport (4.2.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
    activesupport (4.2.1) lib/active_support/callbacks.rb:164:in `call'
    activesupport (4.2.1) lib/active_support/callbacks.rb:164:in `block in halting'
    activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `call'
    activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `block in call'
    activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `each'
    activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `call'
    activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
    activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
    activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
    actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
    actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
    actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
    activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
    activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
    actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
    activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
    actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
    actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
    actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
    actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
    actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
    actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
    actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
    actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
    actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
    actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
    actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
    actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
    actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
    warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
    warden (1.2.3) lib/warden/manager.rb:34:in `catch'
    warden (1.2.3) lib/warden/manager.rb:34:in `call'
    rack (1.6.1) lib/rack/etag.rb:24:in `call'
    rack (1.6.1) lib/rack/conditionalget.rb:38:in `call'
    rack (1.6.1) lib/rack/head.rb:13:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
    rack (1.6.1) lib/rack/session/abstract/id.rb:225:in `context'
    rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
    activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
    activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
    activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
    activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
    activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
    activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
    activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
    actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
    web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
    railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
    railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
    activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
    activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
    activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
    railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
    rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
    rack (1.6.1) lib/rack/runtime.rb:18:in `call'
    activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
    rack (1.6.1) lib/rack/lock.rb:17:in `call'
    actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
    rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
    railties (4.2.1) lib/rails/engine.rb:518:in `call'
    railties (4.2.1) lib/rails/application.rb:164:in `call'
    rack (1.6.1) lib/rack/lock.rb:17:in `call'
    rack (1.6.1) lib/rack/content_length.rb:15:in `call'
    rack (1.6.1) lib/rack/handler/webrick.rb:89:in `service'
    /ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
    /ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
    /ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'


    Rendered /ruby-2.2.2/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.6ms)
    Rendered /ruby-2.2.2/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.6ms)
    Rendered /ruby-2.2.2/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.2ms)
    Rendered /ruby-2.2.2/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (71.4ms)
    Rendered /ruby-2.2.2/gems/web-console-2.1.2/lib/web_console/templates/_markup.html.erb (0.4ms)
    Rendered /ruby-2.2.2/gems/web-console-2.1.2/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.4ms)
    Rendered /ruby-2.2.2/gems/web-console-2.1.2/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.5ms)
    Rendered /ruby-2.2.2/gems/web-console-2.1.2/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.4ms)
    Rendered /ruby-2.2.2/gems/web-console-2.1.2/lib/web_console/templates/console.js.erb within layouts/javascript (68.2ms)
    Rendered /ruby-2.2.2/gems/web-console-2.1.2/lib/web_console/templates/main.js.erb within layouts/javascript (0.4ms)
    Rendered /ruby-2.2.2/gems/web-console-2.1.2/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.6ms)
    Rendered /ruby-2.2.2/gems/web-console-2.1.2/lib/web_console/templates/index.html.erb (161.9ms)
    ```

**Comment by krainboltgreene** [comment]
Blah, I was able to reproduce the bug in the wrong way, I'm not done on this issue yet.

**Comment by krainboltgreene** [comment]
Ended up being a missing `"` in one of the meta tags preceding the csrf_meta_tags line. :|
