### ISSUE TITLE
Unable to Initialize the devise gem

### ISSUE THREAD

**Issue by msumeet** [plataformatec/devise#3656]
Hi, I am unable to initialize devise gem. Whenever I try to run bundle exec rails generate devise:install the following error occurs.

```
/home/action/.rvm/gems/ruby-2.1.1@rails4.1.0/gems/railties-4.1.0/lib/rails/application.rb:287:in `initialize!': Application has been already initialized. (RuntimeError)                                                                                                                                                              
        from /home/action/workspace/simplecodecasts_saas/config/environment.rb:9:in `<top (required)>'                                                             
        from /home/action/.rvm/gems/ruby-2.1.1@rails4.1.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'                             
        from /home/action/.rvm/gems/ruby-2.1.1@rails4.1.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `block in require'                    
        from /home/action/.rvm/gems/ruby-2.1.1@rails4.1.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:232:in `load_dependency'                     
        from /home/action/.rvm/gems/ruby-2.1.1@rails4.1.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'                             
        from /home/action/.rvm/gems/ruby-2.1.1@rails4.1.0/gems/spring-1.3.6/lib/spring/application.rb:92:in `preload'                                              
        from /home/action/.rvm/gems/ruby-2.1.1@rails4.1.0/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'                                               
        from /home/action/.rvm/gems/ruby-2.1.1@rails4.1.0/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'                                        
        from /home/action/.rvm/gems/ruby-2.1.1@rails4.1.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'                                                
        from /home/action/.rvm/gems/ruby-2.1.1@rails4.1.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'                                                 
        from /home/action/.rvm/gems/ruby-2.1.1@rails4.1.0/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'                                
        from /home/action/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                
        from /home/action/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                
        from -e:1:in `<main>'      
```

How can I fix this? 
Thank you.

**Comment by josevalim** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by msumeet** [comment]
Hi,
Here is the application. https://github.com/msumeet/simplecodecasts_saas
Pls check the user_authentication branch.

Thank you.

**Comment by pnomolos** [comment]
@msumeet In https://github.com/msumeet/simplecodecasts_saas/blob/master/config/environment.rb you are calling the following twice:

```ruby
require File.expand_path('../application', __FILE__)

# Initialize the Rails application.
Rails.application.initialize!
```

**Comment by msumeet** [comment]
Thank you so much. I removed that duplicate line and it worked.
