### ISSUE TITLE
Undefined method authenticate? for NilClass

### ISSUE THREAD

**Issue by cjmarkham** [plataformatec/devise#3923]
Rails 4.2.5.1
Rspec Rails 3.4.1
Warden 1.2.5
Devise 3.5.5

When running a controller spec which contains a PATCH request I get the following exception.

Undefined method authenticate? for NilClass

Full Stack trace:

```
# /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.5/lib/devise/controllers/sign_in_out.rb:10:in `block in signed_in?'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.5/lib/devise/controllers/sign_in_out.rb:9:in `any?'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.5/lib/devise/controllers/sign_in_out.rb:9:in `signed_in?'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/two_factor_authentication-1.1.4/lib/two_factor_authentication/controllers/helpers.rb:15:in `block in handle_two_factor_authentication'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/two_factor_authentication-1.1.4/lib/two_factor_authentication/controllers/helpers.rb:14:in `any?'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/two_factor_authentication-1.1.4/lib/two_factor_authentication/controllers/helpers.rb:14:in `handle_two_factor_authentication'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:164:in `block in halting'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `block in call'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `each'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:504:in `call'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `block in instrument'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `instrument'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5.1/lib/abstract_controller/base.rb:137:in `process'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionview-4.2.5.1/lib/action_view/rendering.rb:30:in `process'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5.1/lib/action_controller/test_case.rb:639:in `process'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5.1/lib/action_controller/test_case.rb:67:in `process'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.5/lib/devise/test_helpers.rb:19:in `block in process'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.5/lib/devise/test_helpers.rb:72:in `catch'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.5/lib/devise/test_helpers.rb:72:in `_catch_warden'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.5/lib/devise/test_helpers.rb:19:in `process'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5.1/lib/action_controller/test_case.rb:526:in `patch'
     # ./spec/web/controllers/admin/faqs_spec.rb:29:in `block (3 levels) in <top (required)>'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:236:in `instance_exec'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:236:in `block in run'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:478:in `block in with_around_and_singleton_context_hooks'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:435:in `block in with_around_example_hooks'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/hooks.rb:478:in `block in run'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/hooks.rb:618:in `block in run_around_example_hooks_for'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:320:in `call'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-rails-3.4.1/lib/rspec/rails/example/controller_example_group.rb:191:in `block (2 levels) in <module:ControllerExampleGroup>'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:425:in `instance_exec'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:425:in `instance_exec'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/hooks.rb:389:in `execute_with'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:320:in `call'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-rails-3.4.1/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:425:in `instance_exec'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:425:in `instance_exec'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/hooks.rb:389:in `execute_with'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:320:in `call'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/hooks.rb:621:in `run_around_example_hooks_for'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/hooks.rb:478:in `run'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:435:in `with_around_example_hooks'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:478:in `with_around_and_singleton_context_hooks'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:233:in `run'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:581:in `block in run_examples'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:577:in `map'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:577:in `run_examples'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:543:in `run'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:544:in `block in run'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:544:in `map'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:544:in `run'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:119:in `block (3 levels) in run_specs'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:119:in `map'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:119:in `block (2 levels) in run_specs'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:118:in `block in run_specs'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/reporter.rb:77:in `report'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:117:in `run_specs'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:93:in `run'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:78:in `run'
     # /opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:45:in `invoke'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.2/exe/rspec:4:in `<top (required)>'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `block in load'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
     # /opt/boxen/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
     # -e:1:in `<main>'
```

**Comment by dlisboa** [comment]
Same thing happened in the applications I'm working on. It seems this occurred due to a `warden` update (there was a change in the test helpers in the `1.2.5` version). Version `1.2.4` of `warden` makes the tests green again.

An example app with the locked version of `warden` could show that. Right now I can't provide it though, I apologize.

**Comment by jegodwin** [comment]
Same here. Tests requiring auth started failing after the last warden update to 1.2.5. @dlisboa 's suggestion worked for me as well.

**Comment by wbotelhos** [comment]
Yes, `warden` causes it, you can check on this issue: https://github.com/hassox/warden/issues/128#issuecomment-177266346

**Comment by lucasmazza** [comment]
Closing this as it is related to Warden and not Devise. Thanks @dlisboa and @wbotelhos for the clarification :heart:
