### ISSUE TITLE
View generator error with Rails 5 beta 2

### ISSUE THREAD

**Issue by lachlanjc** [plataformatec/devise#3938]
I've been working on a new Rails 5 (beta 2) app with Ruby 2.3.0. I've found that trying to run `rails g devise:views` results in an error:

```
devisetest % rails g devise:views
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Users/lachlanjc/src/devisetest/config/application.rb:7)
/Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/failure_app.rb:9:in `<class:FailureApp>': uninitialized constant ActionController::RackDelegation (NameError)
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/failure_app.rb:8:in `<module:Devise>'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/failure_app.rb:3:in `<top (required)>'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/mapping.rb:122:in `default_failure_app'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/mapping.rb:67:in `initialize'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise.rb:326:in `new'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise.rb:326:in `add_mapping'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:238:in `block in devise_for'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:237:in `each'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:237:in `devise_for'
	from /Users/lachlanjc/src/devisetest/config/routes.rb:2:in `block in <top (required)>'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta2/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta2/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta2/lib/action_dispatch/routing/route_set.rb:371:in `draw'
	from /Users/lachlanjc/src/devisetest/config/routes.rb:1:in `<top (required)>'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/file_update_checker.rb:75:in `execute'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:30:in `run'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application.rb:350:in `initialize!'
	from /Users/lachlanjc/src/devisetest/config/environment.rb:5:in `<top (required)>'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.3/lib/spring/application.rb:92:in `preload'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.3/lib/spring/application.rb:143:in `serve'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.3/lib/spring/application.rb:131:in `block in run'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.3/lib/spring/application.rb:125:in `loop'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.3/lib/spring/application.rb:125:in `run'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.3/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/lachlanjc/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

I've created a [sample app](https://github.com/lachlanjc/devise-views-error-example) with the defaults of Rails 5 and Devise (and a `User` model), and generating the views doesn't work for me. To try to reproduce this error, you could run:

```
git clone https://github.com/lachlanjc/devise-views-error-example && cd devise-views-error-example
rails g devise:views
```

This is probably my own stupid mistake or an issue with my system, but it could also be something reproducible inside Devise. Thanks!

**Comment by lachlanjc** [comment]
I just discovered that I have to explicitly ask for `4.0.0.rc1` in my Gemfile, and then Devise works fine. Sorry for the trouble!
