### ISSUE TITLE
Devise intermittently decides it won't listen to my configuration

### ISSUE THREAD

**Issue by alexiamcdonald** [plataformatec/devise#4016]
Hello,
I'm a little bit confused if it's something I've done wrong configuring devise for our application or if it's devise intermittently deciding it doesn't want to work but I thought I should probably raise it just in case someone else has the same problem.

We are using:
Rails: 4.1.15
Ruby: 2.2.4
Devise: 3.5.6
Warden: 1.2.6

I originally added this code to devise.rb in my initializers folder when I originally saw this problem of the devise mailer not using our helpers and it fixed it:

```
Devise::Mailer.class_eval do
  helper :application
end
```

But today when I pulled in some new work to our app and migrated a bunch of stuff resetting the server, devise decided it wasn't going to use the helper.

I solved the problem by restarting the server again.

This is what the console spat out when this happened:

``` 
  SQL (0.6ms)  INSERT INTO "users" ("admin", "authentication_token", "confirmation_sent_at", "confirmation_token", "created_at", "email", "encrypted_password", "first_name", "gender", "last_name", "mobile", "payroll_identifier", "type", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) RETURNING "id"  [["admin", "t"], ["authentication_token", "xS2oqc5_iXgCs_xTWo6u"], ["confirmation_sent_at", "2016-04-01 03:01:36.276862"], ["confirmation_token", "Mzn3kfnsiHi9onKEjhWk"], ["created_at", "2016-04-01 03:01:36.075934"], ["email", "alexiamcdonald+5@donesafe.com"], ["encrypted_password", "$2a$10$PtRwEY3L3LFjvIQg5MLrEOihqu0KMMirwQFH6IAwCawiFBZvqi5oq"], ["first_name", "Alexia"], ["gender", "Female"], ["last_name", "FIve"], ["mobile", ""], ["payroll_identifier", ""], ["type", "TenantUser"], ["updated_at", "2016-04-01 03:01:36.075934"]]
  Account Load (0.5ms)  SELECT  "public"."accounts".* FROM "public"."accounts"  WHERE "public"."accounts"."schema" = 'demo'  ORDER BY "public"."accounts"."id" ASC LIMIT 1
  Rendered devise/mailer/confirmation_instructions.html.haml within layouts/email (8.8ms)

Devise::Mailer#confirmation_instructions: processed outbound mail in 93.9ms
   (0.4ms)  ROLLBACK
Completed 500 Internal Server Error in 514ms (ActiveRecord: 9.8ms)
[Rollbar] Reporting exception: undefined local variable or method `email_logo_url' for #<#<Class:0x007fc9135b3b08>:0x007fc913552e20>
[Rollbar] Exception not reported because Rollbar is disabled

NameError - undefined local variable or method `email_logo_url' for #<#<Class:0x007fc9135b3b08>:0x007fc913552e20>:
  app/views/layouts/email.html.haml:165:in `_app_views_layouts_email_html_haml__1864461034700016600_70250794945400'
  actionview (4.1.15) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.15) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.15) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.15) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.15) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.15) lib/action_view/template.rb:143:in `render'
  actionview (4.1.15) lib/action_view/renderer/template_renderer.rb:67:in `render_with_layout'
  actionview (4.1.15) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
  actionview (4.1.15) lib/action_view/renderer/template_renderer.rb:17:in `render'
  actionview (4.1.15) lib/action_view/renderer/renderer.rb:46:in `render_template'
  actionview (4.1.15) lib/action_view/renderer/renderer.rb:27:in `render'
  actionview (4.1.15) lib/action_view/rendering.rb:99:in `_render_template'
  actionview (4.1.15) lib/action_view/rendering.rb:82:in `render_to_body'
  actionpack (4.1.15) lib/abstract_controller/rendering.rb:25:in `render'
  actionmailer (4.1.15) lib/action_mailer/base.rb:864:in `block in collect_responses'
  actionmailer (4.1.15) lib/action_mailer/base.rb:878:in `each_template'
  actionmailer (4.1.15) lib/action_mailer/base.rb:860:in `collect_responses'
  actionmailer (4.1.15) lib/action_mailer/base.rb:789:in `mail'
  devise (3.5.6) lib/devise/mailers/helpers.rb:16:in `devise_mail'
  devise (3.5.6) app/mailers/devise/mailer.rb:7:in `confirmation_instructions'
  actionpack (4.1.15) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.15) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.15) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.15) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.15) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.15) lib/action_view/rendering.rb:30:in `process'
  actionmailer (4.1.15) lib/action_mailer/base.rb:580:in `block in process'
  activesupport (4.1.15) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.15) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.15) lib/active_support/notifications.rb:159:in `instrument'
  actionmailer (4.1.15) lib/action_mailer/base.rb:577:in `process'
  actionmailer (4.1.15) lib/action_mailer/base.rb:568:in `initialize'
  actionmailer (4.1.15) lib/action_mailer/base.rb:551:in `method_missing'
  devise (3.5.6) lib/devise/models/authenticatable.rb:167:in `send_devise_notification'
  devise (3.5.6) lib/devise/models/confirmable.rb:116:in `send_confirmation_instructions'
  devise (3.5.6) lib/devise/models/confirmable.rb:172:in `send_on_create_confirmation_instructions'
  activesupport (4.1.15) lib/active_support/callbacks.rb:429:in `block in make_lambda'
  activesupport (4.1.15) lib/active_support/callbacks.rb:224:in `block in halting_and_conditional'
  activesupport (4.1.15) lib/active_support/callbacks.rb:503:in `block in call'
  activesupport (4.1.15) lib/active_support/callbacks.rb:503:in `call'
  activesupport (4.1.15) lib/active_support/callbacks.rb:86:in `run_callbacks'
  activerecord (4.1.15) lib/active_record/callbacks.rb:306:in `_create_record'
  activerecord (4.1.15) lib/active_record/timestamp.rb:57:in `_create_record'
  activerecord (4.1.15) lib/active_record/persistence.rb:484:in `create_or_update'
  activerecord (4.1.15) lib/active_record/callbacks.rb:302:in `block in create_or_update'
  activesupport (4.1.15) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.15) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
  activesupport (4.1.15) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.1.15) lib/active_support/callbacks.rb:86:in `run_callbacks'
  activerecord (4.1.15) lib/active_record/callbacks.rb:302:in `create_or_update'
  activerecord (4.1.15) lib/active_record/persistence.rb:103:in `save'
  bullet (5.0.0) lib/bullet/active_record41.rb:29:in `save_with_bullet'
  activerecord (4.1.15) lib/active_record/validations.rb:51:in `save'
  activerecord (4.1.15) lib/active_record/attribute_methods/dirty.rb:21:in `save'
  activerecord (4.1.15) lib/active_record/transactions.rb:268:in `block (2 levels) in save'
  activerecord (4.1.15) lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
  activerecord (4.1.15) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
  activerecord (4.1.15) lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
  activerecord (4.1.15) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
  activerecord (4.1.15) lib/active_record/transactions.rb:208:in `transaction'
  activerecord (4.1.15) lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
  activerecord (4.1.15) lib/active_record/transactions.rb:268:in `block in save'
  activerecord (4.1.15) lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
  activerecord (4.1.15) lib/active_record/transactions.rb:267:in `save'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/active_record_helper.rb:26:in `block in save'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/transaction.rb:848:in `with_database_metric_name'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent.rb:572:in `with_database_metric_name'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/active_record_helper.rb:25:in `save'
  app/controllers/tenant/admin/users_controller.rb:56:in `create'
  actionpack (4.1.15) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.15) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.15) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.15) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.15) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.15) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
  activesupport (4.1.15) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.1.15) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.15) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.15) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.15) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.1.15) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.15) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.15) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.15) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.15) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.15) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.15) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.15) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.15) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.15) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.15) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.15) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  actionpack (4.1.15) lib/action_dispatch/routing/route_set.rb:48:in `call'
  actionpack (4.1.15) lib/action_dispatch/routing/mapper.rb:45:in `call'
  actionpack (4.1.15) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.15) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.15) lib/action_dispatch/routing/route_set.rb:690:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:408:in `call_app!'
  omniauth-saml (1.5.0) lib/omniauth/strategies/saml.rb:115:in `other_phase'
  omniauth (1.3.1) lib/omniauth/strategy.rb:185:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  omniauth (1.3.1) lib/omniauth/builder.rb:63:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  oink (0.10.1) lib/oink/middleware.rb:17:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  apartment (1.0.2) lib/apartment/elevators/generic.rb:23:in `call'
  app/middleware/subdomain_elevator.rb:21:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  bullet (5.0.0) lib/bullet/rack.rb:12:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  apartment (1.0.2) lib/apartment/reloader.rb:18:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:35:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/flash.rb:254:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/cookies.rb:562:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (4.1.15) lib/active_record/query_cache.rb:36:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (4.1.15) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (4.1.15) lib/active_record/migration.rb:380:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.15) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.15) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rollbar (2.7.1) lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
  rollbar (2.7.1) lib/rollbar.rb:854:in `scoped'
  rollbar (2.7.1) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  rollbar (2.7.1) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.1.15) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.15) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.15) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.15) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.15) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.15) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activesupport (4.1.15) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.1.15) lib/action_dispatch/middleware/static.rb:84:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.1.15) lib/rails/engine.rb:514:in `call'
  railties (4.1.15) lib/rails/application.rb:144:in `call'
  newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.4) lib/thin/connection.rb:53:in `process'
  thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
  thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.4) lib/thin/server.rb:162:in `start'
  rack (1.5.5) lib/rack/handler/thin.rb:16:in `run'
  rack (1.5.5) lib/rack/server.rb:264:in `start'
  railties (4.1.15) lib/rails/commands/server.rb:69:in `start'
  railties (4.1.15) lib/rails/commands/commands_tasks.rb:81:in `block in server'
  railties (4.1.15) lib/rails/commands/commands_tasks.rb:76:in `server'
  railties (4.1.15) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  railties (4.1.15) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `<main>'



Started POST "/__better_errors/d377d726fc57bc57/variables" for 127.0.0.1 at 2016-04-01 14:01:36 +1100
```

**Comment by josevalim** [comment]
Does it happen every time? Or it happened once and it no longer happens? If it happened once, can you provide a way to reproduce the error?

**Comment by alexiamcdonald** [comment]
It appears to only happen after a migration. I'm able to reproduce it when I create new migrations or I'm pulling in new work that requires I run migrations. I of course have to reset the server when I run migrations but the error appears to happen in that first run. It fixes itself after I reset the server again. It's all very confusing sorry.

**Comment by ulissesalmeida** [comment]
@alexiamcdonald Thank you for your report. 

Well, Devise::Mailer inheritances by default from `ActionMailer::Base`.
If you are using some different class to have your helper methods you may want to change the inheritance using this config:

```ruby
config.parent_mailer = 'MyMailerClass'
```

I don't know if this configuration fits for your use case. If you succeed in reproduce the error let us know.

**Comment by ulissesalmeida** [comment]
@alexiamcdonald I'm closing this issue. Feel free to reopen if you find a way to reproduce the error.
Best
