### ISSUE TITLE
Parent mailer + undefined method

### ISSUE THREAD

**Issue by thiagogsr** [plataformatec/devise#4329]
Hi,

I'm trying to create a mailer to send emails through Sengrid API, so I created a `SendgridMailer` class with the `mail` method and update the `Devise.parent_mailer` to my `SendgridMailer`.

When I try call `user.send_confirmation_instructions` an error is raised.

```
*** NoMethodError Exception: undefined method `confirmation_instructions' for Devise::Mailer:Class
```

 I'm using the `devise_token_auth` gem but it calls the [super](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/models/devise_token_auth/concerns/user.rb#L60-L76) method:

```ruby
send_devise_notification(:confirmation_instructions, @raw_confirmation_token, opts)
```

The stacktrace is:

```
from /Users/thiago/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise-4.2.0/lib/devise/models/authenticatable.rb:188:in `send_devise_notification'
	from /Users/thiago/.dotfiles/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise_token_auth-0.1.39/app/models/devise_token_auth/concerns/user.rb:75:in `send_confirmation_instructions'
	from (irb):5
	from /Users/thiago/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
	from /Users/thiago/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/thiago/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/thiago/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/thiago/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/thiago/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/thiago/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/thiago/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/thiago/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/thiago/Projects/rails/carrot/bin/rails:9:in `<top (required)>'
```

Does anyone know why this error?

**Comment by thiagogsr** [comment]
I think the `ActionMailer::Base` "converts" the instance methods from mailer to class methods because [here](https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/devise/models/authenticatable.rb#L188) it is calling the class method and it works.
