### ISSUE TITLE
Error invalid argument: nil after upgrading to Rails 5

### ISSUE THREAD

**Issue by jarkelen** [plataformatec/devise#4347]
I upgraded to Rails 5 and after starting the server the login forms must be loaded. Then this error occurs:

````
ArgumentError - invalid argument: nil.:
  activerecord (5.0.0.1) lib/active_record/relation/spawn_methods.rb:36:in `merge'
  activerecord (5.0.0.1) lib/active_record/scoping/default.rb:119:in `block (2 levels) in build_default_scope'
  activerecord (5.0.0.1) lib/active_record/scoping/default.rb:117:in `block in build_default_scope'
  activerecord (5.0.0.1) lib/active_record/scoping/default.rb:141:in `evaluate_default_scope'
  activerecord (5.0.0.1) lib/active_record/scoping/default.rb:116:in `build_default_scope'
  activerecord (5.0.0.1) lib/active_record/scoping/named.rb:33:in `default_scoped'
  activerecord (5.0.0.1) lib/active_record/scoping/named.rb:28:in `all'
  activerecord (5.0.0.1) lib/active_record/scoping.rb:24:in `scope_attributes'
  activerecord (5.0.0.1) lib/active_record/scoping.rb:36:in `populate_with_current_scope_attributes'
  activerecord (5.0.0.1) lib/active_record/scoping.rb:43:in `initialize_internals_callback'
  activerecord (5.0.0.1) lib/active_record/core.rb:317:in `initialize'
  activerecord (5.0.0.1) lib/active_record/inheritance.rb:65:in `new'
  devise (4.2.0) app/controllers/devise/sessions_controller.rb:9:in `new'
````

That seems to come from Devise I think?
After searching I found someone with the same error:

````
Turns it it was a gem which behind the scenes was attempting to do default_scope { nil }, looks like someone implemented protection against that (since it shouldn't really work)
````

What should I do?

**Comment by rubyrider** [comment]
Let me try to reproduce. Which version of devise you are using currently ?

**Comment by rubyrider** [comment]
With the given rails version 5.0.0.1 and devise 4.2.0 I can not reproduce this issue. Can you create an application and provide the steps to reproduce that issue?

My test application to reproduce this error is here:
https://github.com/rubyrider/devise-testing-issue-4347
