### ISSUE TITLE
Rails 5.1.1 "undefined method `ref' for ActiveSupport::Dependencies:Module"

### ISSUE THREAD

**Issue by deanpcmad** [plataformatec/devise#4544]
On a new Rails 5.1.1 app with the Devise gem installed, running any Rails commands throws this error:

```
rails generate devise:install
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'devise'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `ref' for ActiveSupport::Dependencies:Module
Backtrace for gem load error is:
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/devise-1.1.8/lib/devise.rb:193:in `mailer='
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/devise-1.1.8/lib/devise.rb:195:in `<module:Devise>'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/devise-1.1.8/lib/devise.rb:4:in `<top (required)>'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/runtime.rb:82:in `require'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/runtime.rb:77:in `each'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/runtime.rb:77:in `block in require'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/runtime.rb:66:in `each'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/runtime.rb:66:in `require'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler.rb:108:in `require'
/Users/dean/bookmarks/config/application.rb:7:in `<top (required)>'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/command/actions.rb:15:in `require'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/commands/generate/generate_command.rb:19:in `perform'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
/Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:9:in `require'
bin/rails:9:in `<main>'
Bundler Error Backtrace:
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/runtime.rb:77:in `each'
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/runtime.rb:77:in `block in require'
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/runtime.rb:66:in `each'
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/runtime.rb:66:in `require'
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler.rb:108:in `require'
	from /Users/dean/bookmarks/config/application.rb:7:in `<top (required)>'
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/command/actions.rb:15:in `require'
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/commands/generate/generate_command.rb:19:in `perform'
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
	from /Users/dean/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
```

**Comment by deanpcmad** [comment]
Skip this. For some reason it was installing version 1.1.8 of devise, not the latest?!
