### ISSUE TITLE
Error sending password reset email

### ISSUE THREAD

**Issue by lloydwatkin** [plataformatec/devise#4547]
> May 26 15:09:11 ip-11-0-1-49 olio-staging[22510]: NoMethodError (undefined method `delay' for Devise::Mailer:Class#012Did you mean?  delegate):#012  lib/devise_backgrounder.rb:22:in `deliver'#012  app/controllers/api/v1/users_controller.rb:21:in `reset_password'

Line 21 in the controller:

```ruby
user.send_reset_password_instructions
```

Ruby 2.4.0
Rails 4.2.8

Same for both devise 4.2.1 and 4.3.0

**Comment by lloydwatkin** [comment]
Used instructions here, https://github.com/plataformatec/devise#activejob-integration and set up mailer queue, so all good now.
