### ISSUE TITLE
failure_app is null on tests

### ISSUE THREAD

**Issue by yosiat** [plataformatec/devise#4622]
Hi,

I am using Devise 4.0.3 (with Rails 4.2.9) and in tests sometimes, I am getting an error:
```
      undefined method `call' for nil:NilClass
./vendor/bundle/ruby/2.4.0/gems/devise-4.0.3/lib/devise/test_helpers.rb:113:in `_process_unauthenticated'
./vendor/bundle/ruby/2.4.0/gems/devise-4.0.3/lib/devise/test_helpers.rb:91:in `_catch_warden'
./vendor/bundle/ruby/2.4.0/gems/devise-4.0.3/lib/devise/test_helpers.rb:19:in `process'
./vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_controller/test_case.rb:520:in `post'
./spec/controllers/hello_controller_spec.rb:97:in `block (3 levels) in <top (required)>'
./vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:254:in `instance_exec'
./vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:254:in `block in run'
./vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:496:in `block in with_around_and_singleton_context_hooks'
./vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:453:in `block in with_around_example_hooks'
./vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:464:in `block in run'
./vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:604:in `block in run_around_example_hooks_for'
```

If I go to this line, I see that `Devise.warden_config[:failure_app]` is nil -
https://github.com/plataformatec/devise/blob/v4.0.3/lib/devise/test_helpers.rb#L113

My test have before each that have `sign_in` and in the test itself we do `sign_out`, and in the devise initializer, we set the failure app to be `CustomFailure`.

Any reason why this should happen?

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
