### ISSUE TITLE
ActiveSupport::Concern::MultipleIncludedBlocks / Eager Loading with Custom Devise Model

### ISSUE THREAD

**Issue by hwhelchel** [plataformatec/devise#4651]
I'm working on a devise integration and have written a custom devise model that validates the user's phone number called PhoneNumberValidatable. It's based off the Email Validatable model.

When running a standalone action cable server I'm consistently getting an error about including the PhoneNumberValidatable `included` block multiple times in my User model.

I've made a [sample rails app that demos the bug](https://github.com/hwhelchel/devise-eager-load-custom-model-bug/pull/1/files). Please view the PR, bundle, and run `foreman s` to see the error.

I tried a `cable/config.ru` with

```ruby
require_relative '../config/environment'
Rails.application.eager_load!

run Rails.application
```

as well but the error persists.

When I comment / uncomment the eager loading of lib in my application.rb file the error goes away.

Would like to understand if I need to reconfigure my  setup or if this is a bug.

I appreciate your time and thought.

-Harry

Error trace:

```
01:27:53 cable.1 | /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/concern.rb:126:in `included': Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
01:27:53 cable.1 |       from /Users/Hoyt/Documents/Code/foo/lib/devise/models/phone_confirmable.rb:46:in `<module:PhoneConfirmable>'
01:27:53 cable.1 |       from /Users/Hoyt/Documents/Code/foo/lib/devise/models/phone_confirmable.rb:43:in `<module:Models>'
01:27:53 cable.1 |       from /Users/Hoyt/Documents/Code/foo/lib/devise/models/phone_confirmable.rb:2:in `<module:Devise>'
01:27:53 cable.1 |       from /Users/Hoyt/Documents/Code/foo/lib/devise/models/phone_confirmable.rb:1:in `<top (required)>'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `load'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `block in load_file'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:661:in `new_constants_in'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:475:in `load_file'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:374:in `block in require_or_load'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `block in load_interlock'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:11:in `loading'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `load_interlock'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:357:in `require_or_load'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:335:in `depend_on'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:251:in `require_dependency'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:475:in `each'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:475:in `block in eager_load!'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:473:in `each'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:473:in `eager_load!'
01:27:53 cable.1 |       from cable/config.ru:2:in `block in <main>'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
01:27:53 cable.1 |       from cable/config.ru:in `new'
01:27:53 cable.1 |       from cable/config.ru:in `<main>'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/configuration.rb:314:in `load_rackup'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/configuration.rb:243:in `app'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/runner.rb:148:in `app'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/runner.rb:155:in `start_server'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:262:in `worker'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:126:in `block (2 levels) in spawn_workers'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:126:in `fork'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:126:in `block in spawn_workers'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:122:in `times'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:122:in `spawn_workers'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:200:in `check_workers'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:471:in `run'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/launcher.rb:183:in `run'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cli.rb:77:in `run'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.10.0/bin/puma:10:in `<top (required)>'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/bin/puma:23:in `load'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/bin/puma:23:in `<top (required)>'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/bin/bundle:22:in `load'
01:27:53 cable.1 |       from /Users/Hoyt/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'
^C01:27:54 system  | SIGINT received, starting shutdown
```

**Comment by hwhelchel** [comment]
This `cable/config.ru` is working

```ruby
require_relative '../config/environment'

run ActionCable.server
```

It appears `Rails.application.eager_load!` there and in `application.rb` included the Devise module twice in my User class causing the error.

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
