### ISSUE TITLE
How to disable email in RSpec

### ISSUE THREAD

**Issue by typhoon2099** [plataformatec/devise#4701]
I've just started using the `:confirmable` module but now my unit tests are trying to send out emails, which is failing with the following:
```
NameError:
       undefined local variable or method `app' for #<Devise::Mailer:0x0000000009b83090>
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/rack-test-0.7.0/lib/rack/test/methods.rb:31:in `build_rack_mock_session'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/rack-test-0.7.0/lib/rack/test/methods.rb:27:in `rack_mock_session'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/rack-test-0.7.0/lib/rack/test/methods.rb:42:in `build_rack_test_session'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/rack-test-0.7.0/lib/rack/test/methods.rb:38:in `rack_test_session'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/rack-test-0.7.0/lib/rack/test/methods.rb:46:in `current_session'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/devise-4.3.0/lib/devise/mailers/helpers.rb:17:in `devise_mail'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/devise-4.3.0/app/mailers/devise/mailer.rb:7:in `confirmation_instructions'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/devise-4.3.0/lib/devise/models/authenticatable.rb:191:in `send_devise_notification'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/devise_token_auth-0.1.42/app/models/devise_token_auth/concerns/user.rb:75:in `send_confirmation_instructions'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/devise-4.3.0/lib/devise/models/confirmable.rb:126:in `send_reconfirmation_instructions'
     # ./app/controllers/v1/users_controller.rb:48:in `update'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/devise-4.3.0/lib/devise/test/controller_helpers.rb:33:in `block in process'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/devise-4.3.0/lib/devise/test/controller_helpers.rb:100:in `catch'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/devise-4.3.0/lib/devise/test/controller_helpers.rb:100:in `_catch_warden'
     # /home/vagrant/.rvm/gems/ruby-2.4.2/gems/devise-4.3.0/lib/devise/test/controller_helpers.rb:33:in `process'
     # ./spec/controllers/v1/users_controller_spec.rb:114:in `block (4 levels) in <top (required)>'
```

Do I need to mock something out to get around this? Is so, what?

Thanks

**Comment by ricardoruwer** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
