### ISSUE TITLE
OmniAuth::Strategies::OAuth2::CallbackError (csrf_detected | CSRF detected)

### ISSUE THREAD

**Issue by EdmundMai** [plataformatec/devise#4813]
I'm trying to login through my React Native mobile app using omniauth-facebook.

```
class ApplicationController < ActionController::Base
  include DeviseTokenAuth::Concerns::SetUserByToken
end
```

Notice I have removed `protect_from_forgery`. However, it is still complaining about CSRF:

```

Started POST "/omniauth/facebook/callback?code=EAAEzTblwxJwBAOyFZCeaiZAdW7T8MaoBKfIZAhh4hZCkvusWCIv3oNfgbKs90ZBftIIeZBFxqdsY3KnFmTQ2E9OmU7InwxodTjZAqBN3IsYSi2Sfxs7gHTXxyQjIKKoGc10hbgackbGKFWPPcMrYHrtZCQkQIOEGn4p3sKbIAcXfaQIb7CO6QLLv0yRZAYVHEHtZAZBcogSqePppAZDZD" for 127.0.0.1 at 2018-03-23 15:53:12 -0400
I, [2018-03-23T15:53:12.647051 #53666]  INFO -- omniauth: (facebook) Callback phase initiated.
E, [2018-03-23T15:53:12.647337 #53666] ERROR -- omniauth: (facebook) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
E, [2018-03-23T15:53:12.647552 #53666] ERROR -- omniauth: (facebook) Authentication failure! invalid_credentials: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected

OmniAuth::Strategies::OAuth2::CallbackError (csrf_detected | CSRF detected):

omniauth (1.8.1) lib/omniauth/failure_endpoint.rb:25:in `raise_out!'
omniauth (1.8.1) lib/omniauth/failure_endpoint.rb:20:in `call'
omniauth (1.8.1) lib/omniauth/failure_endpoint.rb:12:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:486:in `fail!'

```

How is devise normally used through APIs? My requests are coming from a mobile app so there is no CSRF token

**Comment by tegon** [comment]
Possibly related to #4801

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
