### ISSUE TITLE
NoMethodError when using Rails.application.routes.recognize_path

### ISSUE THREAD

**Issue by keoghpe** [plataformatec/devise#4860]
## Environment

- Ruby 2.3.3
- Rails 5.1.0
- Devise 4.3.0

## Current behavior

We have two different root paths depending on whether a user is logged in or not:

```
    unauthenticated do
      root 'marketing_site#home', as: :unauthenticated_root
    end

    authenticated :user do
      root 'static_pages#root', as: :authenticated_root
    end
```

I'm currently using Rails `recognise_path` to identify the controller and action a user is visiting. This works fine for other routes in the app, but I get an exception when I pass in the root path:

`Rails.application.routes.recognize_path('localhost:3000')` results in the following error:

```
devise (4.3.0) lib/devise/rails/routes.rb:477:in `block in constraints_for'
actionpack (5.1.0) lib/action_dispatch/routing/mapper.rb:39:in `block in matches?'
actionpack (5.1.0) lib/action_dispatch/routing/mapper.rb:37:in `each'
actionpack (5.1.0) lib/action_dispatch/routing/mapper.rb:37:in `all?'
actionpack (5.1.0) lib/action_dispatch/routing/mapper.rb:37:in `matches?'
actionpack (5.1.0) lib/action_dispatch/routing/route_set.rb:857:in `block in recognize_path'
actionpack (5.1.0) lib/action_dispatch/journey/router.rb:68:in `block in recognize'
actionpack (5.1.0) lib/action_dispatch/journey/router.rb:62:in `each'
actionpack (5.1.0) lib/action_dispatch/journey/router.rb:62:in `recognize'
actionpack (5.1.0) lib/action_dispatch/routing/route_set.rb:847:in `recognize_path'
```

## Expected behavior

`Rails.application.routes.recognize_path('localhost:3000')` should return `=> {:controller=>"marketing_site", :action=>"home"}`

I'm happy to dig in and help fix this issue if a PR would be merged. Thanks for creating an awesome Gem! 😄

**Comment by keoghpe** [comment]
Closing because I realise this was already addressed here: https://github.com/plataformatec/devise/issues/3747
