### ISSUE TITLE
devise-async dependency requirements

### ISSUE THREAD

**Issue by z4ppy** [plataformatec/devise#4874]
## Environment

- Ruby 2.4.1
- Rails 4.2.10
- Devise 4.4.*

## Current behavior
On user save :

*An* `ArgumentError` *occurred while* `POST </admin/organisms/1/users>` *was processed by* `users#create`
Exception
wrong number of arguments (given 3, expected 1..2)

/home/user/.rvm/gems/ruby-2.4.1/gems/devise-async-0.7.0/lib/devise/async/model.rb:27:in `send_devise_notification'
/home/user/.rvm/gems/ruby-2.4.1/gems/devise-4.4.0/lib/devise/models/confirmable.rb:121:in `send_confirmation_instructions'
/home/user/.rvm/gems/ruby-2.4.1/gems/devise-4.4.0/lib/devise/models/confirmable.rb:183:in `send_on_create_confirmation_instructions'
/home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
/home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:506:in `block in call'
/home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:506:in `each'
/home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:506:in `call'
/home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'

## Expected behavior

Don't update devise if requirement isn't good.
I can't update devise-async without updating rails (devise-async 0.7.0)

**Comment by z4ppy** [comment]
Finally it is not a bug concerning Devise but rather Devise-async
