### ISSUE TITLE
Can't use a custom authentication strategy

### ISSUE THREAD

**Issue by Mcdostone** [plataformatec/devise#4936]
## Description
I want to use devise with an LDAP authentication strategy. I followed literally this wiki to configure everything: [How To: Authenticate via LDAP](https://github.com/plataformatec/devise/wiki/How-To:-Authenticate-via-LDAP). However, this article seems to be outdated because it's not working properly

## Environment

- Ruby **2.5.1p57**
- Rails **5.2.1**
- Devise **4.5**

## Behavior

I got this error when I run the server:

```
11: from /home/mcdostone/X/app/models/user.rb:3:in `<main>'
10: from /home/mcdostone/X/app/models/user.rb:4:in `<class:User>'
...
/home/mcdostone/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:74:in `block in load_missing_constant': uninitialized constant 
Devise::Models::LdapAuthenticatable (NameError)
```

Here the ruby code I wrote:
```ruby

# config/initializers/ldap_authenticatable.rb
require 'devise/strategies/authenticatable'

module Devise
  module Strategies
    class LdapAuthenticatable < Authenticatable
      def authenticate!
        # chunk of code...
      end

      def email
        params[:user][:email]
      end

      def password
        params[:user][:password]
      end
    end
  end
end
Warden::Strategies.add(:ldap_authenticatable, Devise::Strategies::LdapAuthenticatable)


# config/initializers/devise.rb
  config.warden do |manager|
    manager.strategies.add(:ldap_authenticatable, Devise::Models::LdapAuthenticatable)
    manager.default_strategies(scope: :user).unshift :ldap_authenticatable
  end


# app/models/user.rb
class User < ApplicationRecord
  devise :ldap_authenticatable
end

```

**Comment by Mcdostone** [comment]
Here the solution:

```ruby
# config/initializers/ldpa_authenticatable.rb

module Devise
  module Models
    module LdapAuthenticatable
      extend ActiveSupport::Concern
    end
  end

  module Strategies
    class LdapAuthenticatable < Authenticatable
      def authenticate!
         # chunk of code...
      end

      def username
        params[:user][:username]
      end

      def password
        params[:user][:password]
      end
    end
  end
end

Warden::Strategies.add(:ldap_authenticatable, Devise::Strategies::LdapAuthenticatable)
Devise.add_module(:ldap_authenticatable,
                  route: :session, ## This will add the routes, rather than in the routes.rb
                  strategy: true,
                  controller: :sessions,
                  model: "ldap_authenticatable")

```
