### ISSUE TITLE
exceptions logging in and out with engine and locales

### ISSUE THREAD

**Issue by ljonny18** [plataformatec/devise#4940]
I have a rails engine with locales and using Devise to log in. When logging in I'm seeing the exception: 

No route matches [GET] "/assets"
```
ActionController::RoutingError (No route matches [GET] "/assets"):

actionpack (5.0.7) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:11:in `block in call'
activesupport (5.0.7) lib/active_support/logger_silence.rb:20:in `silence'
activesupport (5.0.7) lib/active_support/logger.rb:63:in `block (3 levels) in broadcast'
activesupport (5.0.7) lib/active_support/logger_silence.rb:20:in `silence'
activesupport (5.0.7) lib/active_support/logger.rb:61:in `block (2 levels) in broadcast'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:11:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7) lib/rails/engine.rb:522:in `call'
rack (2.0.5) lib/rack/handler/webrick.rb:86:in `service'
/Users/jwilliam/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/Users/jwilliam/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/Users/jwilliam/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread
```'

also in the url (after login) I see: "/assets?action=home&controller=is_web_engine%2Fstatic_pages&locale=en"

and with logout, the following: 

No route matches [GET] "/assets"
```
ActionController::RoutingError (No route matches [GET] "/assets"):
  
actionpack (5.0.7) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:11:in `block in call'
activesupport (5.0.7) lib/active_support/logger_silence.rb:20:in `silence'
activesupport (5.0.7) lib/active_support/logger.rb:63:in `block (3 levels) in broadcast'
activesupport (5.0.7) lib/active_support/logger_silence.rb:20:in `silence'
activesupport (5.0.7) lib/active_support/logger.rb:61:in `block (2 levels) in broadcast'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:11:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7) lib/rails/engine.rb:522:in `call'
rack (2.0.5) lib/rack/handler/webrick.rb:86:in `service'
/Users/jwilliam/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/Users/jwilliam/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/Users/jwilliam/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

Note, the actual login and logout appear to be successful, just the redirects seem to break.

Any ideas? 

Thanks,
Jon.

**Comment by tegon** [comment]
Hello @ljonny18, thanks for your report.

By looking at your stack trace, I haven't found any devise code being called. Could this be an issue with other parts of your application?
If you can you provide us a sample application that reproduces the issue in isolation that would help us find the issue.

Thank you!

**Comment by tegon** [comment]
I'm closing this issue because it had no recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
