### ISSUE TITLE
Devise bug with nested controller/model

### ISSUE THREAD

**Issue by jackwa12333** [plataformatec/devise#5000]
Devise seems to have a bug with nested controllers and models. I'm currently trying to make my first application and I'm using devise for authentication. I believe I have all the model relationships defined correctly yet I'm experiencing an issue where the user_id attribute isn't being committed to the database. Any help would be greatly appreciated!

```

Started POST "/tickets" for 10.0.0.15 at 2019-01-15 01:09:36 +0000

Cannot render console from 10.0.0.15! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

User Load (0.2ms) SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 ORDER BY `users`.`id` ASC LIMIT 1

↳ /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97

Processing by TicketsController#create as HTML

Parameters: {"utf8"=>"✓", "authenticity_token"=>"VZGnpDK59OjZY/UHck0hL4UnxJM9pQPYGzZCleazmmZqJpDP1mbM9L0QJmJdJkiZYRCCOK4nUh6cCOPgfgi4+g==", "ticket"=>{"category"=>"Product - Expired & Recertification", "deadline"=>"2019-01-15", "messages_attributes"=>{"0"=>{"body"=>"fgh"}}}, "button"=>""}

(0.1ms) BEGIN

↳ app/controllers/tickets_controller.rb:32

Ticket Create (0.2ms) INSERT INTO `tickets` (`category`, `deadline`, `created_at`, `updated_at`) VALUES ('Product - Expired & Recertification', '2019-01-15', '2019-01-15 01:09:36', '2019-01-15 01:09:36')

↳ app/controllers/tickets_controller.rb:32

Message Create (0.7ms) INSERT INTO `messages` (`ticket_id`, `body`, `created_at`, `updated_at`) VALUES (103, 'fgh', '2019-01-15 01:09:36', '2019-01-15 01:09:36')

↳ app/controllers/tickets_controller.rb:32

(44.8ms) ROLLBACK

↳ app/controllers/tickets_controller.rb:32

Completed 500 Internal Server Error in 65ms (ActiveRecord: 46.9ms)

ActiveRecord::NotNullViolation (Mysql2::Error: Field 'user_id' doesn't have a default value: INSERT INTO `messages` (`ticket_id`, `body`, `created_at`, `updated_at`) VALUES (103, 'fgh', '2019-01-15 01:09:36', '2019-01-15 01:09:36')):

app/controllers/tickets_controller.rb:32:in `block in create'

app/controllers/tickets_controller.rb:31:in `create'
```

ticket.rb

```
class Ticket < ApplicationRecord
has_many :messages #, inverse_of: :ticket
has_many :users, through: :messages
accepts_nested_attributes_for :messages
end
```

message.rb

```
class Message < ApplicationRecord
belongs_to :user, optional: true #, inverse_of: :messages
belongs_to :ticket #, inverse_of: :messages
#validates_presence_of :user, :ticket
end
```

user.rb

```
class User < ApplicationRecord
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
devise :database_authenticatable, :registerable,
:trackable, :rememberable, :validatable
has_many :messages #, inverse_of: :user
has_many :tickets, through: :messages
end
```

tickets_controller.rb
```

def new
@ticket = Ticket.new
@ticket.messages.new
end
def create
@ticket = Ticket.new(ticket_params)
@message = @ticket.messages.new
@message.assign_attributes(:user_id => 1)
respond_to do |format|
if @ticket.save
format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
format.json { render :show, status: :created, location: @ticket }
else
format.html { render :new }
format.json { render json: @ticket.errors, status: :unprocessable_entity }
end
end
end
```

```
def ticket_params
params.require(:ticket).permit(:category, :deadline, :status, messages_attributes: [:user_id, :body])
end
```

**Comment by tegon** [comment]
Hello @jackwa12333, thanks for reporting this.

As far as I saw, there's no Devise code involved in this, right? It looks like you're hitting a custom controller (`tickets_controller.rb`) and creating other entities - not a user.

If that's the case I'm not sure how Devise can be causing this issue.

**Comment by sebscholl** [comment]
Hey Jackwa -

I agree with Tegon that it looks like Devise isn't in the cards here. You're code does look a little odd though.

Looking at your terminal output, your `messages_attributes` param is pointing to an Object. `accepts_nested_attributes_for` expects an array of objects to come through as nested params. So that's one thing to explore.

**Comment by tegon** [comment]
I'm closing this issue because it had no recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
