### ISSUE TITLE
sign_in in controllers helpers not working

### ISSUE THREAD

**Issue by alejomongua** [plataformatec/devise#5097]
## Environment

- Ruby 2.6.3
- Rails 5.2.3
- Devise 4.6.2

## Current behavior

When I try the simplest example of sign_in test in a controller's test

```ruby
require 'test_helper'

class EventosControllerTest < ActionDispatch::IntegrationTest
  include Devise::Test::ControllerHelpers
  def setup
    @persona = Persona.create(primer_nombre: "foobar", identificacion: 1234567)
    @user = Usuario.create(email: "user@example.com", persona_id: @persona.id,
                     password: "foobar", password_confirmation: "foobar")
    @persona_admin = Persona.create(primer_nombre: "BarFoo", identificacion: 12345678)
    @admin = Usuario.create(email: "user@exampl.com", persona_id: @persona_admin.id,
                     password: "foobar", password_confirmation: "foobar", profile: 4)
    @evento = eventos(:one)
  end

  test "should redirect index when not logged in" do
    get eventos_path
    assert_redirected_to new_usuario_session
  end

  test "should redirect index when logged in as standard user" do
    sign_in @user
    get eventos_path
    assert_redirected_to new_usuario_session
  end
end
```

It throws this error:

```
NoMethodError:         NoMethodError: undefined method `env' for nil:NilClass
        Did you mean?  end
            /home/alejo/.rvm/gems/ruby-2.6.3/gems/devise-4.6.2/lib/devise/test/controller_helpers.rb:42:in `setup_controller_for_warden'
            /home/alejo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
            /home/alejo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
            /home/alejo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
            /home/alejo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:605:in `catch'
            /home/alejo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:605:in `block in default_terminator'
            /home/alejo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:199:in `block in halting'
            /home/alejo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
            /home/alejo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `each'
            /home/alejo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `invoke_before'
            /home/alejo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:131:in `run_callbacks'
            /home/alejo/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.3/lib/active_support/testing/setup_and_teardown.rb:41:in `before_setup'
            /home/alejo/.rvm/gems/ruby-2.6.3/gems/actionpack-5.2.3/lib/action_dispatch/testing/integration.rb:314:in `before_setup'
            /home/alejo/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/test_help.rb:46:in `before_setup'
```

I can see than @request is nil and this causes the problem

## Expected behavior

It should simulate the user's login

**Comment by trendwithin** [comment]
@alejomongua There was a change in approach to controller testing between Rails 4 and Rails 5. First paragraph under 'Controller tests' notes that for Rails 5 use: `include Devise::Test::IntegrationHelpers`

**Comment by tegon** [comment]
That's correct, the tests should use `Devise::Test::IntegrationHelpers` now.

**Comment by alejomongua** [comment]
Ok, I see.

I this information should be updated on README,md and on the wiki.

Thank you
