### ISSUE TITLE
Devise doesn't work with the latest version of the Ruby (ruby 2.6.3) and macOS Catalina?

### ISSUE THREAD

**Issue by udodihor** [plataformatec/devise#5160]
Hi all! I'm new to this gem so maybe it was already solved (actually I can't find an answer).
Maybe someone can help me with this issue?

## Environment

- Ruby **[ruby 2.6.3]**
- Rails **[Rails 6.0.0]**
- Devise **[devise 4.7.1]**
- MacOS **[Catalina 15.0]**

## Behaviour
After installing devise gem, I try to run next command `rails generate devise:install` and then I got the next trace:
```
/Users/pentagon/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/message_encryptor.rb:206:in `rescue in _decrypt': ActiveSupport::MessageEncryptor::InvalidMessage (ActiveSupport::MessageEncryptor::InvalidMessage)
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/message_encryptor.rb:183:in `_decrypt'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/message_encryptor.rb:157:in `decrypt_and_verify'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/messages/rotator.rb:21:in `decrypt_and_verify'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/encrypted_file.rb:80:in `decrypt'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/encrypted_file.rb:43:in `read'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/encrypted_configuration.rb:21:in `read'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/encrypted_configuration.rb:33:in `config'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/encrypted_configuration.rb:38:in `options'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/core_ext/module/delegation.rb:297:in `method_missing'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/secret_key_finder.rb:24:in `key_exists?'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/secret_key_finder.rb:10:in `find'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/rails.rb:37:in `block in <class:Engine>'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0/lib/rails/initializable.rb:32:in `instance_exec'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0/lib/rails/initializable.rb:32:in `run'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `call'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0/lib/rails/initializable.rb:60:in `run_initializers'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0/lib/rails/application.rb:363:in `initialize!'
        from /Users/pentagon/Desktop/Projects/collabfield/config/environment.rb:5:in `<main>'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/zeitwerk-2.2.0/lib/zeitwerk/kernel.rb:23:in `require'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
        from /Users/pentagon/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:106:in `preload'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:157:in `serve'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/pentagon/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'
```

## Expected behavior
Hope to finish devise configuration and start creating new Models.

Thanks.

**Comment by mracos** [comment]
Hi @udodihor!

It doesn't look like a problem in devise, maybe it's something on your rails setup?
Could be related to your [`credentials.yml.enc` file](https://github.com/rails/rails/issues/31397#issuecomment-387561117)? There's [an issue that really looks like your problem](https://github.com/plataformatec/devise/issues/4904#issuecomment-406136766) and was the rails setup. :smile:

If it turns out to be something on us, you can open a new issue with a sample application that reproduces the problem in isolation or even use the [bug report template](https://github.com/plataformatec/devise/blob/master/guides/bug_report_templates/integration_test.rb).

Thanks!

**Comment by udodihor** [comment]
Thanks, it fixed my problem!
