### ISSUE TITLE
Rails Generators don't work with latest Rails 6 having zeitwerk intergration

### ISSUE THREAD

**Issue by schnmudgal** [plataformatec/devise#5177]
## Environment

- Ruby **2.6.3**
- Rails **6.0.2.1**
- Devise **4.7.1** (happening even with 4.7.0)

## Current behavior

Multiple rails generators are not working anymore after I upgraded successfully from Rails 5.2 to Rails 6.0.1.2. My application works altogether without any problem. Following are the generators I tried which threw errors.

1. `rails webpacker:install`
2. `rails action_text:install`

Following is the error stack (it tried to initialise object because `devise routes` are set up in `routes.rb`.):

```
...
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.2.1/lib/active_support/inflector/methods.rb:280:in `constantize'
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.2.1/lib/active_support/dependencies/zeitwerk_integration.rb:19:in `constantize'
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise.rb:320:in `get'
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/mapping.rb:83:in `to'
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/mapping.rb:78:in `modules'
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/mapping.rb:95:in `routes'
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/mapping.rb:162:in `default_used_route'
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/mapping.rb:72:in `initialize'
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise.rb:350:in `new'
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise.rb:350:in `add_mapping'
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/rails/routes.rb:243:in `block in devise_for'
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/rails/routes.rb:242:in `each'
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/rails/routes.rb:242:in `devise_for'
/Users/sachin/Documents/Data/dib-eight/config/routes.rb:4:in `block in <main>'
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:429:in `instance_exec'
/Users/sachin/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:429:in `eval_block'
...
```

## Expected behavior
Generator commands should work properly.

**Comment by schnmudgal** [comment]
Nevermind. It was stupid master.key issue which was bugging devise and thereby other things.
